### PR TITLE
Setup project with jest and webpack

### PR DESCRIPTION
**Pull request by amentetteh**
Opened for:

- webpack config added
- jest test enabled

### CODE REVIEW

**Review by enoqueJonas — CHANGES_REQUESTED** [review]
# Status: Invalid Pull Request
### Hi @amentetteh 
While you made a great effort, I cannot proceed with the review. The linters are not passing.

Cheers and happy coding👨🏾‍💻.

Feel free to leave any questions in the comments, and tag me so I can respond to them faster.

**Review by enoqueJonas — COMMENTED** [review]
**Tip**: Add all [necessary linters](https://github.com/enoqueJonas/Leaderboard/blob/dev/.github/workflows/linters.yml). That way the codebase follows all of the standard and good practices, that way other developers can work with this code with little trouble.

**Comment by amentetteh** [comment]
Hello @enoqueJonas. Thanks very much for the feedback. Issue fixed.

**Review by enoqueJonas — APPROVED** [review]
Hi @amentetteh , there's nothing more to say other than... It's time to merge it. Congratulations

# Status: Approved🥳

## Highlights
- Good follow up 

Cheers and happy coding👨🏾‍💻

Feel free to ask any questions in the comments. Tag me so I can answer them faster.

**Pull request merged**
