### PR TITLE
Display Comments pop up with selected item's details 

### PR DESCRIPTION
**Pull request by enoqueJonas**
# [[4pt] - Display Comments pop up with selected item's details 

# This PR was raised to:
- Display comments popup

## What does this PR do:
- Create a comments popup only with the top section (displaying details of the selected item)
- When the popup loads, the webapp retrieves data from the selected API and shows details about the selected item.
- Add a Loading animation when the popup is loading

## Improvements to be made
- Add the rest of the information that has to be displayed on the popup

### CODE REVIEW

**Review by amentetteh — COMMENTED** [review]
Hi @enoqueJonas , I can see you made a great effort in the project but a lttle bit improvement
# Status: requires changes
- Consider using fontawesome for icons to follow what we decided earlier
- Rename js files in lowercase to macth the initial logic
- Move views files inside views folder to keep our logic.
- Your're  working with a dev branch very very behind.  Update to avoid huge lerge conflicts 

Cheers and happy coding👨🏾‍💻.

*Feel free to leave any questions in the comments and tag me so I can see and answer faster.*

**Comment by enoqueJonas** [comment]
Hello @amentetteh, 
- About fontawesome icons, I think it is an optional thing, It is not in the project requirements
- About file names, I like to name my files like this

**Comment by amentetteh** [comment]
@enoqueJonas, it is a team work! We decided it before [here](https://github.com/enoqueJonas/Capstone-Module-2/issues/19).
You create the project on your github but it is a common project. It is then not your files  but ours! Otherwise, nothing else to say than, do what you want on your only behalf.

**Comment by enoqueJonas** [comment]
Hello @amentetteh, what rule are you following to name the files? Kindly share with me the link to the standard you are following.
About the fontawesome icons, I will make the changes, but now the focus is to finish a working project because we do not have much time, after finishing and passing the block, we can make the project prettier.

**Comment by amentetteh** [comment]
Hello @enoqueJonas. We're the last day! You must keep the pace to get approval today before evening in our timezones. As I said  it, file naming is not the matter, but your answer. After, we can discus about this. Let go forward.

**Review by amentetteh — APPROVED** [review]

**Review by amentetteh — APPROVED** [review]
# STATUS: APPROVED 🟢
## Hi @enoqueJonas , 
Congratulations!GIF

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- GitHub flow is used correctly. ✔
- All linters checks are ok. ✔

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------

**Pull request merged**
